FactoryBot.define do
  factory :third_party do
    entity { "" }
    name { "" }
    name_alias { "" }
    address { "" }
    zip { "" }
    town { "" }
    status { "" }
    state_id { "" }
    phone { "" }
    fax { "" }
    email { "" }
    socialnetworks { "" }
    url { "" }
    barcode { "" }
    idprof { "" }
    idprof { "" }
    idprof { "" }
    idprof { "" }
    idprof { "" }
    idprof { "" }
    tva_assuj { "" }
    tva_intra { "" }
    localtax1_assuj { "" }
    localtax1_value { "" }
    localtax2_assuj { "" }
    localtax2_value { "" }
    managers { "" }
    capital { "" }
    typent_id { "" }
    typent_code { "" }
    effectif { "" }
    effectif_id { "" }
    forme_juridique_code { "" }
    forme_juridique { "" }
    remise_percent { "" }
    remise_supplier_percent { "" }
    mode_reglement_supplier_id { "" }
    cond_reglement_supplier_id { "" }
    transport_mode_supplier_id { "" }
    fk_prospectlevel { "" }
    date_modification { "" }
    user_modification { "" }
    date_creation { "" }
    user_creation { "" }
    client { "" }
    prospect { "" }
    fournisseur { "" }
    code_client { "" }
    code_fournisseur { "" }
    code_compta_client { "" }
    code_compta { "" }
    accountancy_code_customer { "" }
    code_compta_fournisseur { "" }
    accountancy_code_supplier { "" }
    code_compta_product { "" }
    note_private { "" }
    note_public { "" }
    stcomm_id { "" }
    stcomm_picto { "" }
    status_prospect_labelNever { "MyString" }
    contacted { "" }
    price_level { "" }
    outstanding_limit { "" }
    order_min_amount { "" }
    supplier_order_min_amount { "" }
    parent { "" }
    default_lang { "" }
    ref { "" }
    ref_ext { "" }
    import_key { "" }
    webservices_url { "" }
    webservices_key { "" }
    logo { "" }
    logo_small { "" }
    logo_mini { "" }
    logo_squarred { "" }
    logo_squarred_small { "" }
    logo_squarred_mini { "" }
    accountancy_code_sell { "" }
    accountancy_code_buy { "" }
    fk_multicurrency { "" }
    fk_warehouse { "" }
    multicurrency_codeCAD { "" }
    partnerships { "" }
    bank_account { "" }
    validateFieldsErrors { "" }
    array_options { "" }
    array_languages { "" }
    linkedObjectsIds { "" }
    canvas { "" }
    fk_project { "" }
    contact_id { "" }
    user { "" }
    origin { "" }
    origin_id { "" }
    statut { "" }
    country_id { "" }
    country_code { "" }
    region_id { "" }
    barcode_type { "" }
    barcode_type_coder { "" }
    mode_reglement_id { "" }
    cond_reglement_id { "" }
    demand_reason_id { "" }
    transport_mode_id { "" }
    shipping_method_id { "" }
    model_pdf { "" }
    last_main_doc { "" }
    fk_bank { "" }
    fk_account { "" }
    lastname { "" }
    firstname { "" }
    civility_id { "" }
    date_validation { "" }
    specimen { "" }
    fk_incoterms { "" }
    label_incoterms { "" }
    location_incoterms { "MyString" }
  end
end
