development:
  SMS_APPID: "22002"
  SMS_APPKEY: 10bad57df936ee10411356826e5e7cbf
  SMS_PROJECT: gMbMk
  SMS_PROJECT2: 0qzxe1

production:
  SMS_APPID: "22002"
  SMS_APPKEY: 10bad57df936ee10411356826e5e7cbf
  SMS_PROJECT: gMbMk
  SMS_PROJECT2: 0qzxe1
