class CreateThirdParties < ActiveRecord::Migration[6.1]
  def change
    create_table :third_parties do |t|
      t.string :entity
      t.string :name
      t.string :name_alias
      t.string :address
      t.string :zip
      t.string :town
      t.string :status
      t.string :state_id
      t.string :phone
      t.string :fax
      t.string :email
      t.string :url
      t.string :barcode
      t.string :tva_assuj
      t.string :tva_intra
      t.string :managers
      t.string :capital
      t.string :typent_id
      t.string :typent_code
      t.string :effectif
      t.string :effectif_id
      t.string :forme_juridique_code
      t.string :forme_juridique
      t.string :remise_percent
      t.string :remise_supplier_percent
      t.string :fk_prospectlevel
      t.integer :date_modification
      t.string :user_modification
      t.integer :date_creation
      t.string :user_creation
      t.string :client
      t.string :prospect
      t.string :fournisseur
      t.string :note_private
      t.string :note_public
      t.string :stcomm_id
      t.string :stcomm_picto
      t.string :contacted
      t.integer :price_level
      t.string :outstanding_limit
      t.string :order_min_amount
      t.string :supplier_order_min_amount
      t.string :parent
      t.string :default_lang
      t.string :ref
      t.string :ref_ext
      t.string :import_key
      t.string :webservices_url
      t.string :webservices_key
      t.string :logo
      t.string :logo_small
      t.string :logo_mini
      t.string :logo_squarred
      t.string :logo_squarred_small
      t.string :logo_squarred_mini
      t.string :accountancy_code_sell
      t.string :accountancy_code_buy
      t.string :fk_multicurrency
      t.string :fk_warehouse
      t.string :multicurrency_codeCAD
      t.string :bank_account
      t.string :linkedObjectsIds
      t.string :canvas
      t.string :fk_project
      t.string :contact_id
      t.string :user
      t.string :origin
      t.string :origin_id
      t.string :statut
      t.string :country_id
      t.string :country_code
      t.string :region_id
      t.string :model_pdf
      t.string :last_main_doc
      t.string :fk_bank
      t.string :fk_account
      t.string :lastname
      t.string :firstname
      t.string :civility_id
      t.integer :date_validation
      t.string :specimen
      t.string :fk_incoterms
      t.string :label_incoterms
      t.string :location_incoterms
      t.string :promote_code

      t.timestamps
    end
  end
end
